# Generated by Django 4.1.2 on 2022-11-09 05:41

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='dislikes',
            new_name='average_rating',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='likes',
            new_name='total_ratings',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(db_index=True, default='aaaaaaaaaaaaaaaaaaaaa', max_length=22, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('track_number', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
                ('artist', models.ManyToManyField(to='spotify.artist')),
            ],
        ),
    ]
