from django.db import migrations, models
import django.db.models.deletion

def add_college_dropout(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    jay_z = Artist.objects.filter(spotify_id='3nFkdlSjzX9mRTtwJOzDYB').first()
    album = Album.objects.filter(spotify_id='4Uv86qWpGTxf7fU7lG5X6F').first()
    syleena = Artist.objects.create(spotify_id='1lE6SEy8f84Zhjvp7r8yTD', name='Syleena Johnson')
    glc = Artist.objects.create(spotify_id='2hZ6jVi1cao5VlJHAEPzU7', name='GLC')
    consequence = Artist.objects.create(spotify_id='5KkgZ31b9eDwkvo9oMIrSm', name='Consequence')
    jivy = Artist.objects.create(spotify_id='0hKpvarswO34Ks5iPNmEXn', name='J. Ivy')
    talib = Artist.objects.create(spotify_id='0lEssBAxQl2In4RpaB1C2Y', name='Talib Kweli')
    common = Artist.objects.create(spotify_id='2GHclqNVjqGuiE5mA7BEoc', name='Common')
    twista = Artist.objects.create(spotify_id='6vbY3hOaCAhC7VjucswgdS', name='Twista')
    jamie = Artist.objects.create(spotify_id='7LnaAXbDVIL75IVPnndf7w', name='Jamie Foxx')
    ludacris = Artist.objects.create(spotify_id='3ipn9JLAPI5GUEo4y4jcoi', name='Ludacris')
    mos_def = Artist.objects.create(spotify_id='0Mz5XE0kb1GBnbLQm2VbcO', name='Mos Def')
    freeway = Artist.objects.create(spotify_id='2Jwr7hGoSNK3S3QBxh3T0z', name='Freeway')
    choir = Artist.objects.create(spotify_id='7Cp14KBRtDwGucKNPUyT11', name='The Boys Choir of Harlem')
    Song.objects.create(spotify_id='7lIr3vVhpDkU5mQEDcnA0S', name='Intro', track_number=1, duration_ms=19133, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0IW0qaeyxL5Et4UG2MrJKB', name="We Don't Care", track_number=2, duration_ms=239880, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7wL7Lb8Q3aYyq6gmRL0PZq', name='Graduation Day', track_number=3, duration_ms=81786, album=album).artist.add(kanye, syleena)
    Song.objects.create(spotify_id='5SkRLpaGtvYPhw02vZhQQ9', name='All Falls Down', track_number=4, duration_ms=223506, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6MgGapP3EPFm9kYUvYBTZR', name="I'll Fly Away", track_number=5, duration_ms=69706, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1ko2NuvWlQdxtNRc8QQzmT', name='Spaceship', track_number=6, duration_ms=324226, album=album).artist.add(kanye, glc, consequence)
    Song.objects.create(spotify_id='5g1vtHqi9uV7xtYeCcFOBx', name='Jesus Walks', track_number=7, duration_ms=193733, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='34j4OxJxKznBs88cjSL2j9', name='Never Let Me Down', track_number=8, duration_ms=324440, album=album).artist.add(kanye, jay_z, jivy)
    Song.objects.create(spotify_id='5b2FFKC64kxqcfaFnIZxoM', name='Get Em High', track_number=9, duration_ms=289493, album=album).artist.add(kanye, talib, common)
    Song.objects.create(spotify_id='2a1JSfTePKhysdIif2bzut', name='Workout Plan', track_number=10, duration_ms=46173, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1Vp4St7JcXaUoJcIahtf3L', name='The New Workout Plan', track_number=11, duration_ms=322800, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3A4cpTBPaIQdtPFb5JxtaX', name='Slow Jamz', track_number=12, duration_ms=316053, album=album).artist.add(kanye, twista, jamie)
    Song.objects.create(spotify_id='4KFY4EEv9CN6ivrzD6vEvg', name='Breathe In Breathe Out', track_number=13, duration_ms=246933, album=album).artist.add(kanye, ludacris)
    Song.objects.create(spotify_id='25mwJPzWVmS2yronBNQJF1', name='School Spirit Skit 1', track_number=14, duration_ms=78693, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1th3G3okofWlvGWAAR7Y4V', name='School Spirit', track_number=15, duration_ms=182386, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5MAY7XyW322jMwLDtBQgsZ', name='School Spirit Skit 2', track_number=16, duration_ms=43533, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4BhwlQ9mTwhFGXpQvP9JTV', name='Lil Jimmy Skit', track_number=17, duration_ms=53640, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='62wtttQzoIA9HnNmGVd9Yq', name='Two Words', track_number=18, duration_ms=266213, album=album).artist.add(kanye, mos_def, freeway, choir)
    Song.objects.create(spotify_id='4mmkhcEm1Ljy1U9nwtsxUo', name='Through The Wire', track_number=19, duration_ms=221226, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5DBmXF7QO43Cuy9yqva116', name='Family Business', track_number=20, duration_ms=278893, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7iOhWWYjhhQiXzF4o4HhXN', name='Last Call', track_number=21, duration_ms=760973, album=album).artist.add(kanye)

def add_late_registration(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    jay_z = Artist.objects.filter(spotify_id='3nFkdlSjzX9mRTtwJOzDYB').first()
    glc = Artist.objects.filter(spotify_id='2hZ6jVi1cao5VlJHAEPzU7').first()
    consequence = Artist.objects.filter(spotify_id='5KkgZ31b9eDwkvo9oMIrSm').first()
    common = Artist.objects.filter(spotify_id='2GHclqNVjqGuiE5mA7BEoc').first()
    jamie = Artist.objects.filter(spotify_id='7LnaAXbDVIL75IVPnndf7w').first()
    album = Album.objects.filter(spotify_id='5ll74bqtkcXlKE7wwkMq4g').first()
    adam = Artist.objects.create(spotify_id='4bYPcJP5jwMhSivRcqie2n', name='Adam Levine')
    lupe = Artist.objects.create(spotify_id='01QTIT5P1pFP3QnnFSdsJf', name='Lupe Fiasco')
    paul = Artist.objects.create(spotify_id='0k7Xl1pqI3tu8sSEjo5oEg', name='Paul Wall')
    game = Artist.objects.create(spotify_id='0NbfKEOTQCcwd6o7wSDOHI', name='The Game')
    brandy = Artist.objects.create(spotify_id='05oH07COxkXKIMt6mIPRee', name='Brandy')
    nas = Artist.objects.create(spotify_id='20qISvAhX20dpIbOOzGK3q', name='Nas')
    really = Artist.objects.create(spotify_id='69m0yjx8ruKebsRvbNuEDz', name='Really Doe')
    camron = Artist.objects.create(spotify_id='7iMvwE8qANp3aIfAGKEAwS', name="Cam'ron")
    Song.objects.create(spotify_id='62KeM7jbmYvzT5FycdiQeS', name='Wake Up Mr. West', track_number=1, duration_ms=41066, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6yIjtVtnOBeC8SwdVHzAuF', name="Heard 'Em Say", track_number=2, duration_ms=203733, album=album).artist.add(kanye, adam)
    Song.objects.create(spotify_id='2dxjKgT0li4qBI3QwuN9Ih', name='Touch The Sky', track_number=3, duration_ms=236600, album=album).artist.add(kanye, lupe)
    Song.objects.create(spotify_id='1PS1QMdUqOal0ai3Gt7sDQ', name='Gold Digger', track_number=4, duration_ms=207626, album=album).artist.add(kanye, jamie)
    Song.objects.create(spotify_id='164al00XRSLWG6h4hc12bD', name='Skit #1', track_number=5, duration_ms=33573, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6vB49BJ70zBpDrrAPwdaB8', name='Drive Slow', track_number=6, duration_ms=272226, album=album).artist.add(kanye, paul, glc)
    Song.objects.create(spotify_id='0TzIHqhAbvYR6qJKrMMFlk', name='My Way Home', track_number=7, duration_ms=103373, album=album).artist.add(kanye, common)
    Song.objects.create(spotify_id='4fRTe59xEeNHT4uyAGsV27', name='Crack Music', track_number=8, duration_ms=270866, album=album).artist.add(kanye, game)
    Song.objects.create(spotify_id='2DHNCWZYmVr1Lv08q5b0kB', name='Roses', track_number=9, duration_ms=245866, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='25K9cWrxNv991UYiOzBJqR', name='Bring Me Down', track_number=10, duration_ms=198973, album=album).artist.add(kanye, brandy)
    Song.objects.create(spotify_id='5VzeI5JM2y9t21JwrWAnkH', name='Addiction', track_number=11, duration_ms=267066, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='466XcSgGAiQxcDrcV0yoMP', name='Skit #2', track_number=12, duration_ms=31360, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='34KUIBsIUiPV7oCIzSdDAU', name='Diamonds From Sierra Leone - Remix', track_number=13, duration_ms=233400, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='46fk9wjYcPm0sgym2b7EEE', name='We Major', track_number=14, duration_ms=448000, album=album).artist.add(kanye, nas, really)
    Song.objects.create(spotify_id='2Xn5DIyAba7Fgyky3gU3rA', name='Skit #3', track_number=15, duration_ms=24133, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='46OFHBw45fNi7QNjSetITR', name='Hey Mama', track_number=16, duration_ms=305066, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7jAxGkXU58FwNMjqoMahn7', name='Celebration', track_number=17, duration_ms=198440, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3zXhvJaLpxefYIxBE0cnB0', name='Skit #4', track_number=18, duration_ms=78666, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5RjbFGeWVsCpw8EcE8OrvZ', name='Gone', track_number=19, duration_ms=333293, album=album).artist.add(kanye, consequence, camron)
    Song.objects.create(spotify_id='4R5bSS8yoCl2czeWLr61aO', name='Diamonds From Sierra Leone - Bonus Track', track_number=20, duration_ms=238400, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1mFHMzbaECWFaPfoePoEYl', name='Late', track_number=21, duration_ms=230493, album=album).artist.add(kanye)

def add_graduation(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    mos_def = Artist.objects.filter(spotify_id='0Mz5XE0kb1GBnbLQm2VbcO').first()
    album = Album.objects.filter(spotify_id='4SZko61aMnmgvNhfhgTuD3').first()
    tpain = Artist.objects.create(spotify_id='3aQeKQSyrW4qWr35idm0cy', name='T-Pain')
    lil_wayne = Artist.objects.create(spotify_id='55Aa2cqylxrFIXC767Z865', name='Lil Wayne')
    dwele = Artist.objects.create(spotify_id='7u6LfVyYpEzMpHLL7jTyvU', name='Dwele')
    dj = Artist.objects.create(spotify_id='6GEykX11lQqp92UVOQQCC7', name='DJ Premier')
    chris = Artist.objects.create(spotify_id='0LQoZQIV0mIs0y0XQb0Sw2', name='Chris Martin')
    albe = Artist.objects.create(spotify_id='1i4q97Tz8xmGWJps51J7WT', name='Albe Back')
    Song.objects.create(spotify_id='6MXXY2eiWkpDCezVCc0cMH', name='Good Morning', track_number=1, duration_ms=195093, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4UQMOPSUVJVicIQzjAcRRZ', name='Champion', track_number=2, duration_ms=167600, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0j2T0R9dR9qdJYsB7ciXhf', name='Stronger', track_number=3, duration_ms=311866, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7rbECVPkY5UODxoOUVKZnA', name='I Wonder', track_number=4, duration_ms=243440, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4ZPdLEztrlZqbJkgHNw54L', name='Good Life', track_number=5, duration_ms=207000, album=album).artist.add(kanye, tpain)
    Song.objects.create(spotify_id='0mEdbdeRFQwBhN4xfyIeUM', name="Can't Tell Me Nothing", track_number=6, duration_ms=271600, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7387VaiHpOsSIZ5nmjseya', name='Barry Bonds', track_number=7, duration_ms=204306, album=album).artist.add(kanye, lil_wayne)
    Song.objects.create(spotify_id='7DRuzSlhjKadgdsQRYZ0tr', name='Drunk and Hot Girls', track_number=8, duration_ms=313226, album=album).artist.add(kanye, mos_def)
    Song.objects.create(spotify_id='5TRPicyLGbAF2LGBFbHGvO', name='Flashing Lights', track_number=9, duration_ms=237506, album=album).artist.add(kanye, dwele)
    Song.objects.create(spotify_id='0NrtwAmRAdLxua31SzHvXr', name='Everything I Am', track_number=10, duration_ms=227893, album=album).artist.add(kanye, dj)
    Song.objects.create(spotify_id='0lWjRSzq5chA9fps3pM8Zr', name='The Glory', track_number=11, duration_ms=212706, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4iz9lGMjU1lXS51oPmUmTe', name='Homecoming', track_number=12, duration_ms=203493, album=album).artist.add(kanye, chris)
    Song.objects.create(spotify_id='2L47m9erkB5KBZcaqWtYen', name='Big Brother', track_number=13, duration_ms=287560, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3bhyo2ED5Yd4RLydQBDtD6', name='Good Night', track_number=14, duration_ms=185973, album=album).artist.add(kanye, mos_def, albe)

def add_808s(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    kid_cudi = Artist.objects.filter(spotify_id='0fA0VVWsXO9YnASrzqfmYu').first()
    album = Album.objects.filter(spotify_id='3WFTGIO6E3Xh4paEOBY9OU').first()
    lil_wayne = Artist.objects.filter(spotify_id='55Aa2cqylxrFIXC767Z865').first()
    jeezy = Artist.objects.create(spotify_id='4yBK75WVCQXej1p04GWqxH', name='Jeezy')
    hudson = Artist.objects.create(spotify_id='1zV9UjTUevjp5VUddqIUUn', name='Mr Hudson')
    Song.objects.create(spotify_id='5e5MKPtJuFb8NaeSEyV5gD', name='Say You Will', track_number=1, duration_ms=377600, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3F18I7LhWKxlf1PytSoTBH', name='Welcome To Heartbreak', track_number=2, duration_ms=262933, album=album).artist.add(kanye, kid_cudi)
    Song.objects.create(spotify_id='4EWCNWgDS8707fNSZ1oaA5', name='Heartless', track_number=3, duration_ms=211000, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0m3Ze0cy8qBHSsV2exAfCw', name='Amazing', track_number=4, duration_ms=238333, album=album).artist.add(kanye, jeezy)
    Song.objects.create(spotify_id='1kxeWHF9PrCVZHvVskv8lg', name='Love Lockdown', track_number=5, duration_ms=270306, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0w2piYWj1F2bzUftzGJgK9', name='Paranoid', track_number=6, duration_ms=277906, album=album).artist.add(kanye, hudson)
    Song.objects.create(spotify_id='02LAK7qT1wya0klSeNO96f', name='RoboCop', track_number=7, duration_ms=274360, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6j8gTlbhj9KJSeypNcNAS9', name='Street Lights', track_number=8, duration_ms=189906, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1nNPoG2hygEvrFGlHdhvJ9', name='Bad News', track_number=9, duration_ms=238773, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5zuoz1NBnpoHK6g5sbEH8F', name='See You In My Nightmares', track_number=10, duration_ms=258120, album=album).artist.add(kanye, lil_wayne)
    Song.objects.create(spotify_id='2RRFTLIglxHgAYQzsSLI4Y', name='Coldest Winter', track_number=11, duration_ms=164333, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6giHsGo1eSYZSXKdNwTC62', name='Pinocchio Story', track_number=12, duration_ms=361600, album=album).artist.add(kanye)

def add_watch_the_throne(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    jay_z = Artist.objects.filter(spotify_id='3nFkdlSjzX9mRTtwJOzDYB').first()
    hudson = Artist.objects.filter(spotify_id='1zV9UjTUevjp5VUddqIUUn').first()
    album = Album.objects.filter(spotify_id='7mCeLbChyegbRwwKK5shJs').first()
    frank = Artist.objects.create(spotify_id='2h93pZq0e7k5yf4dywlkpM', name='Frank Ocean')
    dream = Artist.objects.create(spotify_id='1W3FSF1BLpY3hlVIgvenLz', name='The-Dream')
    beyonce = Artist.objects.create(spotify_id='6vWDO969PvNqNYHIOW5v0m', name='Beyoncé')
    otis = Artist.objects.create(spotify_id='60df5JBRRPcnSpsIMxxwQm', name='Otis Redding')
    Song.objects.create(spotify_id='3Osd3Yf8K73aj4ySn6LrvK', name='No Church In The Wild', track_number=1, duration_ms=272506, album=album).artist.add(kanye, jay_z, frank, dream)
    Song.objects.create(spotify_id='08T26i7SErk6jCDTW7uUFI', name='Lift Off', track_number=2, duration_ms=266253, album=album).artist.add(kanye, jay_z, beyonce)
    Song.objects.create(spotify_id='4Li2WHPkuyCdtmokzW2007', name='Ni**as In Paris', track_number=3, duration_ms=219333, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='6vegnfDS8DAEaCqWaPYGPy', name='Otis', track_number=4, duration_ms=178213, album=album).artist.add(kanye, jay_z, otis)
    Song.objects.create(spotify_id='5Pt83OUaK3K9C2if4C5JOk', name='Gotta Have It', track_number=5, duration_ms=140746, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='3SIgBSv9D8Nm3CvP0o0Q9Z', name='New Day', track_number=6, duration_ms=272853, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='3TJxCXkL774hhGUmzFLUgy', name="That's My Bitch", track_number=7, duration_ms=202560, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='6N43Qgg9jx21vfMkTYvSi3', name='Welcome To The Jungle', track_number=8, duration_ms=174133, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='3R1k8P1MrDdLSRhlTaaWAS', name='Who Gon Stop Me', track_number=9, duration_ms=256706, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='1smcSwXObpmxcjCulmjMgy', name='Murder To Excellence', track_number=10, duration_ms=300960, album=album).artist.add(kanye, jay_z)
    Song.objects.create(spotify_id='4Mx5gDSGBHbrsgJR7r1QwJ', name='Made In America', track_number=11, duration_ms=292066, album=album).artist.add(kanye, jay_z, frank)
    Song.objects.create(spotify_id='4lLmG1fatRUgnRz0Ol0WUi', name='Why I Love You', track_number=12, duration_ms=201373, album=album).artist.add(kanye, jay_z, hudson)

def add_yeezus(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    album = Album.objects.filter(spotify_id='7D2NdGvBHIavgLhmcwhluK').first()
    Song.objects.create(spotify_id='1gqkRc9WtOpnGIqxf2Hvzr', name='On Sight', track_number=1, duration_ms=156480, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='722tgOgdIbNe3BEyLnejw4', name='Black Skinhead', track_number=2, duration_ms=188013, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0HMCdlOPJkAGlB0MlSWIcO', name='I Am A God', track_number=3, duration_ms=231506, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4cAgkb0ifwn0FSHGXnr4F6', name='New Slaves', track_number=4, duration_ms=256093, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5nIu0VwPOsjkF61zfevLKh', name='Hold My Liquor', track_number=5, duration_ms=326946, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='52NmkyHsGsHGb1UX8fTkMg', name="I'm In It", track_number=6, duration_ms=234853, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='42GcjriRK6srwHkfbkBqVl', name='Blood On The Leaves', track_number=7, duration_ms=359800, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5nPOM0nFRAJ3XI8xCxNAzO', name='Guilt Trip', track_number=8, duration_ms=243746, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3RKblQNJs8HPvWBgXmq6nn', name='Send It Up', track_number=9, duration_ms=178040, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3sNVsP50132BTNlImLx70i', name='Bound 2', track_number=10, duration_ms=229146, album=album).artist.add(kanye)

def add_mbdtf(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    kid_cudi = Artist.objects.filter(spotify_id='0fA0VVWsXO9YnASrzqfmYu').first()
    jay_z = Artist.objects.filter(spotify_id='3nFkdlSjzX9mRTtwJOzDYB').first()
    album = Album.objects.filter(spotify_id='20r762YmB5HeofjMCiPMLv').first()
    pusha_t = Artist.objects.create(spotify_id='0ONHkAv9pCAFxb0zJwDNTy', name='Pusha T')
    raekwon = Artist.objects.create(spotify_id='2yQf6b8hxahZaT5dHlWaB1', name='Raekwon')
    rick = Artist.objects.create(spotify_id='1sBkRIssrMs1AbVkOJbc7a', name='Rick Ross')
    nicki = Artist.objects.create(spotify_id='0hCNtLu0JehylgoiP8L4Gh', name='Nicki Minaj')
    bon = Artist.objects.create(spotify_id='4LEiUm1SRbFMgfqnQTwUbQ', name='Bon Iver')
    cyhi = Artist.objects.create(spotify_id='18HVMQsV3tINaTyzT5UIjH', name='CyHi')
    swizz = Artist.objects.create(spotify_id='2cADQgiLMjNhbsfeN52Bf3', name='Swizz Beatz')
    rza = Artist.objects.create(spotify_id='4iCwCMnqsNZ6atvRiADgtn', name='RZA')
    john = Artist.objects.create(spotify_id='5y2Xq6xcjJb2jVM54GHK3t', name='John Legend')
    Song.objects.create(spotify_id='7yNK27ZTpHew0c55VvIJgm', name='Dark Fantasy', track_number=1, duration_ms=280786, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='23SZWX2IaDnxmhFsSLvkG2', name='Gorgeous', track_number=2, duration_ms=357653, album=album).artist.add(kanye, kid_cudi, raekwon)
    Song.objects.create(spotify_id='2gZUPNdnz5Y45eiGxpHGSc', name='POWER', track_number=3, duration_ms=292093, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4D6TpthzUVNTjWQqfBW5Kb', name='All Of The Lights (Interlude)', track_number=4, duration_ms=62253, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='22L7bfCiAkJo5xGSQgmiIO', name='All Of The Lights', track_number=5, duration_ms=299613, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1ZHYJ2Wwgxes4m8Ba88PeK', name='Monster', track_number=6, duration_ms=378893, album=album).artist.add(kanye, jay_z, rick, nicki, bon)
    Song.objects.create(spotify_id='6K07Ahf6V7CAQn0ikrOztl', name='So Appalled', track_number=7, duration_ms=397666, album=album).artist.add(kanye, jay_z, pusha_t, cyhi, swizz, rza)
    Song.objects.create(spotify_id='1UGD3lW3tDmgZfAVDh6w7r', name='Devil In A New Dress', track_number=8, duration_ms=351946, album=album).artist.add(kanye, rick)
    Song.objects.create(spotify_id='3DK6m7It6Pw857FcQftMds', name='Runaway', track_number=9, duration_ms=547733, album=album).artist.add(kanye, pusha_t)
    Song.objects.create(spotify_id='3rCNmRonlHN1TXQLcG3dSk', name='Hell Of A Life', track_number=10, duration_ms=327786, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4EndPA8b6FDWYp1RgsnLEB', name='Blame Game', track_number=11, duration_ms=469866, album=album).artist.add(kanye, john)
    Song.objects.create(spotify_id='2Im64pIz6m0EJKdUe6eZ8r', name='Lost In The World', track_number=12, duration_ms=256586, album=album).artist.add(kanye, bon)
    Song.objects.create(spotify_id='4e5IPJxSGVWPsaxQzdRseN', name='Who Will Survive In America', track_number=13, duration_ms=98200, album=album).artist.add(kanye)

def add_life_of_pablo(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    album = Album.objects.filter(spotify_id='7gsWAHLeT0w7es6FofOXk1').first()
    Song.objects.create(spotify_id='1eQBEelI2NCy7AUTerX0KS', name='Ultralight Beam', track_number=1, duration_ms=320680, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4KW1lqgSr8TKrvBII0Brf8', name='Father Stretch My Hands Pt. 1', track_number=2, duration_ms=135920, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1Wsbr1d2BouNGk2q92mIj7', name='Pt. 2', track_number=3, duration_ms=130293, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='19a3JfW8BQwqHWUMbcqSx8', name='Famous', track_number=4, duration_ms=196040, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='49fT6owWuknekShh9utsjv', name='Feedback', track_number=5, duration_ms=147240, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='36o4taPyOdnOMf01ERmn9a', name='Low Lights', track_number=6, duration_ms=131773, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4qYLPta5HZ36idWiXtqh7B', name='Highlights', track_number=7, duration_ms=199866, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6wfzokDylbrJzrJcpnBkcy', name='Freestyle 4', track_number=8, duration_ms=123386, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5CGS4UovzA7ftCJkLVXQju', name='I Love Kanye', track_number=9, duration_ms=44826, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3nAq2hCr1oWsIU54tS98pL', name='Waves', track_number=10, duration_ms=181573, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='30Zcjs7pgEkmJA1lEbGSWT', name='FML', track_number=11, duration_ms=236120, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='66Q3fAmSX5eHamgbKa9alP', name='Real Friends', track_number=12, duration_ms=251573, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='432hUIl3ISDeytYW5XBQ5h', name='Wolves', track_number=13, duration_ms=301586, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='20r94xA0bsYNLtYSiOE6r3', name="Frank's Track", track_number=14, duration_ms=38333, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1ZnA4VYOlYIShuGt60LmCs', name='Siiiiiiiiilver Surffffeeeeer Intermission', track_number=15, duration_ms=56560, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='2CHmgtK8OCL28WtIK96u4N', name='30 Hours', track_number=16, duration_ms=323302, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0zLClc0emc6qUeV1p5nc99', name='No More Parties In LA', track_number=17, duration_ms=374413, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3MnbXlC1N7GdS9M8HzA6no', name='Facts (Charlie Heat Version)', track_number=18, duration_ms=200733, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3cCxoOgfi6hgt8MNteuiiD', name='Fade', track_number=19, duration_ms=193747, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1o0kWPueYo94LIjPYOE5Nf', name='Saint Pablo', track_number=20, duration_ms=372113, album=album).artist.add(kanye)

def add_ye(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    album = Album.objects.filter(spotify_id='2Ek1q2haOnxVqhvVKqMvJe').first()
    party = Artist.objects.create(spotify_id='2HPaUgqeutzr3jx5a9WyDV', name='PARTYNEXTDOOR')
    Song.objects.create(spotify_id='0yhxBvedRdGxsPZHJNI4VA', name='I Thought About Killing You', track_number=1, duration_ms=274186, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1qsHYUd2c1wFGcn7e63QmG', name='Yikes', track_number=2, duration_ms=188773, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3U21A07gAloCc4P7J8rxcn', name='All Mine', track_number=3, duration_ms=145506, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1nGoy0cEj0extAwXYNYTWd', name="Wouldn't Leave", track_number=4, duration_ms=205546, album=album).artist.add(kanye, party)
    Song.objects.create(spotify_id='35KV2Nuib6jPMVN00O8iba', name='No Mistakes', track_number=5, duration_ms=123040, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7vgTNTaEz3CsBZ1N4YQalM', name='Ghost Town', track_number=6, duration_ms=271386, album=album).artist.add(kanye, party)
    Song.objects.create(spotify_id='3s7MCdXyWmwjdcWh7GWXas', name='Violent Crimes', track_number=7, duration_ms=215320, album=album).artist.add(kanye)

def add_KIDS_SEE_GHOSTS(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    ksg = Artist.objects.filter(spotify_id='2hPgGN4uhvXAxiXQBIXOmE').first()
    album = Album.objects.filter(spotify_id='6pwuKxMUkNg673KETsXPUV').first()
    pusha_t = Artist.objects.filter(spotify_id='0ONHkAv9pCAFxb0zJwDNTy').first()
    louis = Artist.objects.create(spotify_id='52lBOxCxbJg0ttXEW9CQpW', name='Louis Prima')
    ty_dolla = Artist.objects.create(spotify_id='7c0XG5cIJTrrAgEC3ULPiq', name='Ty Dolla $ign')
    yasiin = Artist.objects.create(spotify_id='6r2niOTnexy9xss5g8GWXH', name='Yasiin Bey')
    Song.objects.create(spotify_id='3aUFrxO1B8EW63QchEl3wX', name='Feel The Love', track_number=1, duration_ms=165053, album=album).artist.add(ksg, pusha_t)
    Song.objects.create(spotify_id='7oHkit3F3vimtsBbnZkU0G', name='Fire', track_number=2, duration_ms=140526, album=album).artist.add(ksg)
    Song.objects.create(spotify_id='6JyEh4kl9DLwmSAoNDRn5b', name='4th Dimension', track_number=3, duration_ms=153351, album=album).artist.add(ksg, louis)
    Song.objects.create(spotify_id='7GRTrWsP3yo2Fx8umJfA1X', name='Freeee (Ghost Town Pt. 2)', track_number=4, duration_ms=206605, album=album).artist.add(ksg, ty_dolla)
    Song.objects.create(spotify_id='4RVbK6cV0VqWdpCDcx3hiT', name='Reborn', track_number=5, duration_ms=324674, album=album).artist.add(ksg)
    Song.objects.create(spotify_id='2I3dW2dCBZAJGj5X21E53k', name='Kids See Ghosts', track_number=6, duration_ms=245098, album=album).artist.add(ksg, yasiin)
    Song.objects.create(spotify_id='4kUZvXB3LC3an3HX6h0s17', name='Cudi Montage', track_number=7, duration_ms=197000, album=album).artist.add(ksg)

def add_JESUS_IS_KING(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    album = Album.objects.filter(spotify_id='0FgZKfoU2Br5sHOfvZKTI9').first()
    choir = Artist.objects.create(spotify_id='2c9O21YLFy4tFI9zCVhbFg', name='Sunday Service Choir')
    ty_dolla = Artist.objects.filter(spotify_id='7c0XG5cIJTrrAgEC3ULPiq').first()
    ant = Artist.objects.create(spotify_id='028lPW2NdWHdSPCkRkcyhd', name='Ant Clemons')
    fred = Artist.objects.create(spotify_id='2ndyVAdV9UqF1XjyTJt484', name='Fred Hammond')
    clipse = Artist.objects.create(spotify_id='2J257euzcjnDLipsyJH3F2', name='Clipse')
    kenny = Artist.objects.create(spotify_id='6I3M904Y9IwgDjrQ9pANiB', name='Kenny G')
    Song.objects.create(spotify_id='1WnqWQcWcuQbVzgE7ecfCY', name='Every Hour', track_number=1, duration_ms=112239, album=album).artist.add(kanye, choir)
    Song.objects.create(spotify_id='39JRmdKFka1Oe09FoOCPI4', name='Selah', track_number=2, duration_ms=164619, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='2QpGZOhTCHHiKmpSO9FW4h', name='Follow God', track_number=3, duration_ms=104591, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3JWiDGQX2eTlFvKj3Yssj3', name='Closed On Sunday', track_number=4, duration_ms=151873, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='2SasoXZyv82yYgHiVOvxQn', name='On God', track_number=5, duration_ms=136350, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='24bnCCysWnbNRNUT4LpHcP', name='Everything We Need', track_number=6, duration_ms=116559, album=album).artist.add(kanye, ty_dolla, ant)
    Song.objects.create(spotify_id='454Epa1vrCGFddHXKyC1kb', name='Water', track_number=7, duration_ms=168419, album=album).artist.add(kanye, ant)
    Song.objects.create(spotify_id='6xRWoYwfwIKnT8bQGzKbxR', name='God Is', track_number=8, duration_ms=203141, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7r6aR2f57resC5r93LwMfK', name='Hands On', track_number=9, duration_ms=203174, album=album).artist.add(kanye, fred)
    Song.objects.create(spotify_id='0oPOuDmmkVp3h6puekhs6P', name='Use This Gospel', track_number=10, duration_ms=213877, album=album).artist.add(kanye, clipse, kenny)
    Song.objects.create(spotify_id='7sBgFMWqDWQgrsNSpIBoe8', name='Jesus Is Lord', track_number=11, duration_ms=49292, album=album).artist.add(kanye)

def add_Donda(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Artist = apps.get_model('spotify', 'Artist')
    Album = apps.get_model('spotify', 'Album')
    Song = apps.get_model('spotify', 'Song')
    kanye = Artist.objects.filter(spotify_id='5K4W6rqBFWDnAN6FQUkS6x').first()
    album = Album.objects.filter(spotify_id='5CnpZV3q5BcESefcB3WJmz').first()
    Song.objects.create(spotify_id='7eSSmgq26BXr7xay3WKjfi', name='Donda Chant', track_number=1, duration_ms=52061, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6d8HN8MqqbqrEUI2bvx0aG', name='Jail', track_number=2, duration_ms=297000, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5JaSg0AYyAMMLjyGGDrrCm', name='God Breathed', track_number=3, duration_ms=333461, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6LNoArVBBVZzUTUiAX2aKO', name='Off The Grid', track_number=4, duration_ms=339249, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='6Hfu9sc7jvv6coyy2LlzBF', name='Hurricane', track_number=5, duration_ms=243187, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0WSEq9Ko4kFPt8yo3ICd6T', name='Praise God', track_number=6, duration_ms=226652, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='35acXjupfWHgtchiS6yAjC', name='Jonah', track_number=7, duration_ms=195170, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5LuXsO34x6KVlL8OWsxRqk', name='Ok Ok', track_number=8, duration_ms=204629, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1jgcODbfAL3tV7tikF6n1j', name='Junya', track_number=9, duration_ms=147668, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='0JuSGEldfovcc8IS9va1wa', name='Believe What I Say', track_number=10, duration_ms=242400, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='68RhNM8ehkarnEKnCkqlsp', name='24', track_number=11, duration_ms=197898, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='45N9i9QraLWD6GW7xBqxnx', name='Remote Control', track_number=12, duration_ms=198613, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7CC6UbCs4iGsePSzFxYxNn', name='Moon', track_number=13, duration_ms=156091, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='2Y40huo5ewaKYxsFintYtF', name='Heaven and Hell', track_number=14, duration_ms=145301, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4jkwu5KQbXXrbAZzVmt5fE', name='Donda', track_number=15, duration_ms=128313, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='7EagormFign5ag6f16ua3I', name='Keep My Spirit Alive', track_number=16, duration_ms=221250, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='1LwdWIbfuqlOo8vlHxkyna', name='Jesus Lord', track_number=17, duration_ms=538536, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='75QktuEju5vz9lyXiLaUao', name='New Again', track_number=18, duration_ms=183296, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='4OfnDoi5VOPsXtwnofq6aL', name='Tell The Vision', track_number=19, duration_ms=104218, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5Iq6pIudd4KfuxZqf8872b', name='Lord I Need You', track_number=20, duration_ms=162108, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5aqUqSq0SqGBAqEn27PEzc', name='Pure Souls', track_number=21, duration_ms=358621, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5xvXeuxISyXJDRbZZf4uzd', name='Come to Life', track_number=22, duration_ms=310393, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='3hd6zLhnTlbJ8PupYt3cAI', name='No Child Left Behind', track_number=23, duration_ms=178061, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='2H8jWuNmluerTEsuh8Gu6y', name='Jail pt 2', track_number=24, duration_ms=297000, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='5ad5uryyzVWs95bK3myGkw', name='Ok Ok pt 2', track_number=25, duration_ms=204629, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='2auYgZ1GcTkWj2bOaE2Wwm', name='Junya pt 2', track_number=26, duration_ms=182635, album=album).artist.add(kanye)
    Song.objects.create(spotify_id='360VkSTITvF55weIKoaNTw', name='Jesus Lord pt 2', track_number=27, duration_ms=690731, album=album).artist.add(kanye)

class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_updates'),
    ]
    
    operations = [
        migrations.RunPython(add_college_dropout),
        migrations.RunPython(add_late_registration),
        migrations.RunPython(add_graduation),
        migrations.RunPython(add_808s),
        migrations.RunPython(add_watch_the_throne),
        migrations.RunPython(add_yeezus),
        migrations.RunPython(add_mbdtf),
        migrations.RunPython(add_life_of_pablo),
        migrations.RunPython(add_ye),
        migrations.RunPython(add_KIDS_SEE_GHOSTS),
        migrations.RunPython(add_JESUS_IS_KING),
        migrations.RunPython(add_Donda),
    ]