# Generated by Django 4.1.2 on 2022-12-20 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0004_alter_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='album',
            name='total_ratings',
        ),
        migrations.CreateModel(
            name='AlbumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='user_ratings',
            field=models.ManyToManyField(related_name='album_ratings', through='spotify.AlbumRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
